TS_SEARCH_PATHS=(~/ghq:4)
TS_EXTRA_SEARCH_PATHS=(~/Developer/)
TS_SESSION_COMMANDS=('bash -c "opencode . --print-logs 2>>/tmp/opencode-psa.log"' 'bash -c "opencode . --print-logs 2>>/tmp/opencode-psa.log"' "image-request")
TS_LOG=filource /Users/milinda/.tmux-sessionizer

