#!/bin/bash

# take screenshot
import -window root /tmp/screenshot.png

# blur it
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
#then remove the tmp file
rm /tmp/screenshot.png

# lock the screen
i3lock -i /tmp/screenshotblur.png
