local builtin = require("telescope.builtin")
local opts = { noremap = true, silent = true }
-- NOTE: convert the grep to ripgrep and find to fd if there are any performance bottlenecks
-- keymaps
vim.keymap.set('n',	'<leader>te', ":Telescope<CR>")
vim.keymap.set('n', '<leader>ps', function()
				require("telescope.builtin").grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader><space>',
	function()
		builtin.find_files({
			no_ignore = false,
			hidden = false
		})
	end)
vim.keymap.set('n', '<leader>gf', builtin.git_files, {})
vim.keymap.set('n', ';r', function()
	builtin.live_grep()
end)
vim.keymap.set('n', '<leader>?', function()
				require("telescope.builtin").current_buffer_fuzzy_find()
end)
vim.keymap.set('n', '<leader>;', function()
				require("telescope.builtin").command_history()
end)
vim.keymap.set('n', '<leader>:', function()
				require("telescope.builtin").commands()
end)
vim.keymap.set('n', '<leader>tr', function()
 builtin.resume()
end)
vim.keymap.set('n', '<leader>bb', function()
				require("telescope.builtin").buffers()
end)
vim.keymap.set('n', ';h', function()
	builtin.help_tags()
end)
vim.keymap.set('n', ';d', function()
	builtin.diagnostics()
end)
vim.keymap.set('n', '<leader>cs', function()
				require("telescope.builtin").lsp_document_symbols()
end)
vim.keymap.set('n', '<leader>fr', function()
				require("telescope.builtin").oldfiles()
end)
vim.keymap.set('n', '<leader>km', function()
				require("telescope.builtin").keymaps()
end)

