#!/bin/bash

# Check if the XDG_SESSION_TYPE environment variable is set to Wayland
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
		while true
		do
				# Use find to get a list of image files in the directory
				images=($(find ~/Pictures//wallpapers-stuff2/* -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \)))

						# Use shuf to select a random image file from the list
						random_image=$(shuf -e "${images[@]}" -n 1)

										# Use swaymsg to set the wallpaper
										swaymsg output "*" bg "$random_image" fill
										sleep 300
								done
						else
								while true
								do
										# Use feh to set a random wallpaper for Xorg
										feh --randomize --bg-scale ~/Pictures/wallpapers-stuff2/*
										sleep 300
								done
fi
